# create your drupal and postgres config here, based off the last assignment
version: "3.1"
services:
  drupal:
    build: .
    image: custom-drupal
    ports:
      - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - /var/lib/postgresql/data
